/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewSalesRecord;

/**
 *
 * @author Black Code
 */
import Forms.ConnectionToDatabase;
import Forms.MainPanel;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class NewSalesRecord extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
String[] productName;
String[] quantity;
double[] amountPerRows;
    /**
     * Creates new form NewSalesRecord
     */
    public NewSalesRecord() {
        initComponents();
        conn = ConnectionToDatabase.connectToDb();
        populateCompany();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
 
    public void close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    public void populateCompany(){
        try{
            String sql = "SELECT company_name FROM company";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
             while(rs.next()){
               companyCombo.addItem(rs.getString("company_name"));
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void populateCategory(){
          productCategoryCombo.removeAllItems();
        try{
            String sql = "SELECT category FROM product_category";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                productCategoryCombo.addItem(rs.getString("category"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quantityTxt = new javax.swing.JTextField();
        productCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        companyCombo = new javax.swing.JComboBox();
        productCategoryCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        doneBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        addToCartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantityTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        quantityTxt.setEnabled(false);
        jPanel1.add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 134, 258, -1));

        productCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        productCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        productCombo.setEnabled(false);
        productCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productComboItemStateChanged(evt);
            }
        });
        productCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboActionPerformed(evt);
            }
        });
        jPanel1.add(productCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 92, 258, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, 118, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, 118, -1));

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Product Category", "Product Name", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(cartTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 176, 1087, 179));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Company Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 118, -1));

        companyCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        companyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        companyCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                companyComboItemStateChanged(evt);
            }
        });
        companyCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                companyComboPropertyChange(evt);
            }
        });
        jPanel1.add(companyCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 6, 258, -1));

        productCategoryCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        productCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        productCategoryCombo.setEnabled(false);
        productCategoryCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productCategoryComboItemStateChanged(evt);
            }
        });
        productCategoryCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                productCategoryComboPropertyChange(evt);
            }
        });
        jPanel1.add(productCategoryCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 50, 258, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Product Category");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, 118, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));

        backBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/Go-back-icon.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 501, 241, 33));

        doneBtn.setBackground(new java.awt.Color(0, 204, 102));
        doneBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        doneBtn.setForeground(new java.awt.Color(255, 255, 255));
        doneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/Accept-icon.png"))); // NOI18N
        doneBtn.setText("Confirm Purchases");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });
        getContentPane().add(doneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 212, 36));

        removeBtn.setBackground(new java.awt.Color(204, 0, 0));
        removeBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/Apps-Dialog-Remove-icon.png"))); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 500, 212, 36));

        addToCartBtn.setBackground(new java.awt.Color(0, 153, 51));
        addToCartBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addToCartBtn.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/shop-cart-add-icon.png"))); // NOI18N
        addToCartBtn.setText("Add to cart");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 500, 212, 36));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Lifeline Medical Store");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesRecord/s.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        model.addRow(new Object[]{companyCombo.getSelectedItem(),productCategoryCombo.getSelectedItem(), productCombo.getSelectedItem(),quantityTxt.getText()});
    
    }//GEN-LAST:event_addToCartBtnActionPerformed
    public int getSum(){
        int rowsCount  = cartTable.getRowCount();
        int sum = 0;
        for(int i=0;i < rowsCount; i++){
            sum = sum+Integer.parseInt(cartTable.getValueAt(i, 3).toString());
        }
        return sum;
    }
    public void insertAllProducts(double val){
       DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calobj = Calendar.getInstance();
        try{
       
            int rowsCount  = cartTable.getRowCount();
            for(int i =0;i < rowsCount; i++){
               String sql  = "INSERT INTO sales_record(product_name,company_name,date_of_sale,quantity,amount) VALUES (?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, cartTable.getValueAt(i, 2).toString());
                pst.setString(2, cartTable.getValueAt(i, 0).toString());
                pst.setString(3, df.format(calobj.getTime()));
                pst.setString(4, cartTable.getValueAt(i, 3).toString());
            }
                 pst.setString(5, String.valueOf(val));
                   pst.execute();
                  
             
                 
                   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    public void getPriceOfProductName(){
       int des = JOptionPane.showConfirmDialog(null, "Confirm Purchase?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(des==0){
             try{
                    int sum= 0;
                    int rowsCount = cartTable.getRowCount();
                    for(int i=0; i<rowsCount;i++){

                        String sql = "SELECT price_per_unit FROM products WHERE product_name='"+cartTable.getValueAt(i, 2).toString()+"'";
                        pst = conn.prepareStatement(sql);
                        rs = pst.executeQuery();
                        if(rs.next()){
                            sum  += Integer.parseInt(cartTable.getValueAt(i, 3).toString()) * Double.parseDouble(rs.getString("price_per_unit"));  
                        
                        }
                        insertAllProducts(Double.parseDouble(cartTable.getValueAt(i, 3).toString()) * Double.parseDouble(rs.getString("price_per_unit")));
                       
                    }
                     JOptionPane.showMessageDialog(null, "Product Added");
                       
                   MainPanel mp = new MainPanel();
                   close();
                   mp.setVisible(true);
              //     JOptionPane.showMessageDialog(null, String.valueOf(sum));

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
       }else{
           
       }
      
    }
    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        getPriceOfProductName();    
    }//GEN-LAST:event_doneBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainPanel mp = new MainPanel();
        close();
        mp.setVisible(true);

    }//GEN-LAST:event_backBtnActionPerformed

    private void companyComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_companyComboItemStateChanged
        populateCategory();
        productCategoryCombo.enable(true);
        productCombo.enable(true);
        productCombo.removeAllItems();
        try{

           String sql = "SELECT product_name FROM products WHERE company_name='"+companyCombo.getSelectedItem()+"'";
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next()){
               productCombo.addItem(rs.getString("product_name"));
           }
 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_companyComboItemStateChanged

    private void productComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productComboItemStateChanged
       
    }//GEN-LAST:event_productComboItemStateChanged

    private void companyComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_companyComboPropertyChange
         quantityTxt.enable(true);
    }//GEN-LAST:event_companyComboPropertyChange

    private void productCategoryComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productCategoryComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_productCategoryComboItemStateChanged

    private void productCategoryComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_productCategoryComboPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_productCategoryComboPropertyChange

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
          DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        if (cartTable.getSelectedRow() != -1) {
            model.removeRow(cartTable.getSelectedRow());
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void productComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSalesRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JComboBox companyCombo;
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox productCategoryCombo;
    private javax.swing.JComboBox productCombo;
    public javax.swing.JTextField quantityTxt;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
